---
swagger: '2.0'
info:
  title: RockClient
  version: 2015-09-01-preview
host: localhost:41067
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  "/api/rock":
    get:
      operationId: ExampleRock
      description: Gets a rock.
      parameters: []
      responses:
        '200':
          description: The rock
          schema:
            "$ref": "#/definitions/rock"
definitions:
  rock:
    properties:
      Name:
        type: string
        description: The rock name.
      Color:
        type: string
        description: The rock color.
      Weight:
        type: number
        format: int32
        description: The rock weight.
